Add reanimated to proguard rules. (#2725)
After upgrading to 2.3.0 i was getting instant crashes on release variants. 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.f.j()' on a null object reference
```

Adding reanimated to proguard rules fixes the issue.